# Generated by Django 6.0.3 on 2026-03-06 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'media',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='api.economicevent')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='api.media')),
            ],
        ),
        migrations.CreateModel(
            name='FramingAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framing_type', models.CharField(choices=[('optimistic', '낙관적'), ('pessimistic', '비관적'), ('alarmist', '경고적'), ('defensive', '방어적'), ('comparative', '비교적'), ('neutral', '중립적')], max_length=20)),
                ('confidence', models.FloatField()),
                ('sentiment_score', models.FloatField()),
                ('bias_score', models.FloatField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='framing', to='api.article')),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('close_price', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('change_rate', models.FloatField()),
            ],
            options={
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
