# Generated by Django 6.1.1 on 2026-09-28 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('date', models.DateField(db_index=True, null=True)),
            ],
            options={
                'ordering': ['-date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('group', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'media',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FramingAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('positive', '긍정'), ('neutral', '중립'), ('negative', '부정')], db_index=True, max_length=10)),
                ('confidence', models.FloatField(null=True)),
                ('reason', models.TextField(blank=True)),
                ('sentiment_score', models.FloatField()),
                ('keyword_polarity', models.FloatField()),
                ('bias_score', models.FloatField(db_index=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='framing', to='api.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='api.media'),
        ),
    ]
